# yaml-language-server: $schema=http://schemas.homeassistant.io/
blueprint:
  name: Disable Heating
  description: Disable thermostat if a window is opened
  domain: automation
  input:
    window_sensor:
      name: Window Sensor
      description: The relevant window
      selector:
        entity:
          filter:
            domain: binary_sensor
          multiple: false
    target_thermostat:
      name: Thermostat
      description: The thermostat to diable if the windows is opened
      selector:
        entity:
          filter:
            domain: climate
  source_url: https://github.com/nostra83/ha-blueprints/blob/14ef7435d0338ef301b331cd3f8cefa41e78bd87/disable-heating.yaml
trigger:
  - trigger: state
    entity_id: !input window_sensor
action:
  - action: climate.set_hvac_mode
    data:
      hvac_mode:
        "{% if trigger.to_state.state == \"on\" %}\n  off\n{% else %}\n  heat\n{%
        endif %}\n"
    target: !input target_thermostat
